language: c
compiler: gcc
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq libncurses-dev
 - sudo apt-get install -qq libslang2-dev
 - sudo apt-get install -qq unzip
install: 
  - wget https://github.com/harbour/core/archive/master.zip -O /tmp/harbour-dev.zip
  - cd /tmp && unzip harbour-dev.zip && cd -
  - cd /tmp/core-master && HB_INSTALL_PREFIX=/usr/local HB_BUILD_3RDEXT=no HB_BUILD_CONTRIBS=xhb sudo make install && cd -
script: hbmk2 ./lib.hbp
